controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    # Declare controllers here
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    healthbot_controller:
      type: diff_drive_controller/DiffDriveController

    # simple_velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

# Parameters for the diff drive controller
healthbot_controller:
  ros__parameters:
    use_stamped_vel: true
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_separation: 0.17
    wheel_radius: 0.033

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    cmd_vel_timeout: 0.5
    base_frame_id: base_footprint
    odom_frame_id: odom
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.7
        min_velocity: -0.7
        has_acceleration_limits: true
        max_acceleration: 0.7
        min_acceleration: -0.7
        has_jerk_limits: false
        max_jerk: 5.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 8.5
        min_velocity: -8.5
        has_acceleration_limits: true
        max_acceleration: 5.0
        min_acceleration: -5.0
        has_jerk_limits: false
        max_jerk: 2.5

# Parameters for the simple velocity controller
# simple_velocity_controller:
#   ros__parameters:
#     joints:
#       - wheel_left_joint
#       - wheel_right_joint
