slam_toolbox:
  ros__parameters:
    # Solver settings
    solver_plugin: solver_plugins::AztecSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY

    # Toolbox settings
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping # Initial mode to build the hospital map

    # Scan Matcher Settings
    max_laser_range: 12.0
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.
